/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package habittrackerapp;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Dashboard extends javax.swing.JFrame {
    private javax.swing.JToggleButton jToggleButton1;
private javax.swing.JToggleButton jToggleButton2;
private javax.swing.JToggleButton jToggleButton3;
private javax.swing.JTextField jTextField1;

   
    

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
       refreshDashboard();
        
        
        
    // Appliquer un léger effet de zoom en réduisant l'écart entre les images
    addZoomEffect(jLabel2, 210, 170, 230, 190);  
    addZoomEffect(jLabel3, 210, 170, 230, 190);
    addZoomEffect(jLabel4, 210, 170, 230, 190);
    





    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // Méthode pour ajouter un effet de zoom en gardant toute l'image visible

// Méthode pour ajouter un léger effet de zoom tout en gardant l'image visible
private void addZoomEffect(JLabel label, int smallWidth, int smallHeight, int bigWidth, int bigHeight) {
    ImageIcon originalIcon = (ImageIcon) label.getIcon(); // Sauvegarde l'icône d'origine

    // Définir l'image en plus petite au départ
    label.setIcon(resizeIcon(originalIcon, smallWidth, smallHeight));
    label.setBounds(label.getX() + (bigWidth - smallWidth) / 4, 
                    label.getY() + (bigHeight - smallHeight) / 4, 
                    smallWidth, smallHeight);

    label.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            // Appliquer un léger zoom
            label.setIcon(resizeIcon(originalIcon, bigWidth, bigHeight));
            label.setBounds(label.getX() - (bigWidth - smallWidth) / 4, 
                            label.getY() - (bigHeight - smallHeight) / 4, 
                            bigWidth, bigHeight);
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            // Revenir à la taille normale
            label.setIcon(resizeIcon(originalIcon, smallWidth, smallHeight));
            label.setBounds(label.getX() + (bigWidth - smallWidth) / 4, 
                            label.getY() + (bigHeight - smallHeight) / 4, 
                            smallWidth, smallHeight);
        }
    });
}

// Méthode pour redimensionner une icône
private ImageIcon resizeIcon(ImageIcon icon, int width, int height) {
    Image img = icon.getImage();  
    Image resizedImage = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);  
    return new ImageIcon(resizedImage);
}
void  refreshDashboard() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);  // Effacer le tableau avant d'ajouter les nouvelles données

    try (Connection conn = DatabaseConnection.connect()) {
        if (conn == null) {
            JOptionPane.showMessageDialog(null, "Database connection failed!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String query = "SELECT Name,Daily_Time,Daily_Frequency, Frequency, Reminder_time, Reminder_frequency FROM Habits";
        PreparedStatement pstmt = conn.prepareStatement(query);
        ResultSet rs = pstmt.executeQuery();

        while (rs.next()) {
            String name = rs.getString("Name");
             String dailyTime = rs.getString("Daily_Time");
             String dailyFreq = rs.getString("Daily_Frequency");
            String frequency = rs.getString("Frequency");
            String reminderTime = rs.getString("Reminder_time");
            String reminderFrequency = rs.getString("Reminder_frequency");
            
             String dailyGoal = dailyTime + " - " + dailyFreq;

            // Combiner Reminder Time et Reminder Frequency dans une seule chaîne
            String reminder = reminderTime + " - " + reminderFrequency;

            model.addRow(new Object[]{name,dailyGoal, frequency, reminder});  // Ajouter les données dans la table
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error loading habits: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Habit", "Daily  goal", "frequency", "Reminder"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 720, 400));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/setbtn.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 360, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/habtn.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 350, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashbtn.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 350, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newbtn.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 250, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/graph.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 230, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ag.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 230, 190));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bell.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 230, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DashPage.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        NewHabit newHabitFrame = new NewHabit();
        newHabitFrame.setVisible(true);
        // Fermer la fenêtre d'inscription actuelle
      
    }//GEN-LAST:event_jLabel5MouseClicked



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
